### ISSUE TITLE
Add content for Hacktoberfest in Open Source Section.

### ISSUE THREAD

**Issue by sahil9001** [FOSSNITRR/fossnitrr.github.io#1]
We want the hacktoberfest info to be added to open-source section of the page. Anyone who could take up this issue is welcomed.

**Comment by mtso** [comment]
What info needs to be added? A link to hacktoberfest.digitalocean.com and a summary describing how to participate?

**Comment by sahil9001** [comment]
@mtso Yeah, a more summarised content for the college (National Institute of Technology, Raipur).

**Comment by possum6** [comment]
I would like to give this a go!

**Comment by possum6** [comment]
I have added a PR for this now :)
